accounts/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'login$', 'accounts.views.persona_login', name='persona_login'),
    url(r'logout$', 'django.contrib.auth.views.logout', {'next_page':'/'}, name='logout'),
    ]

lists/urls.py
from django.conf.urls import url

from lists import views

urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
    url(r'^users/(.+)/$', views.my_lists, name='my_lists'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include('accounts.urls')),
    # url(r'^admin/', include(admin.site.urls)),
]

accounts/models.py
from django.db import models
from django.utils import timezone


class User(models.Model):
    email = models.EmailField(primary_key=True)
    last_login = models.DateTimeField(default=timezone.now)
    REQUIRED_FIELDS = ()
    USERNAME_FIELD = 'email'

    def is_authenticated(self):
        return True

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

class List(models.Model):
    @property
    def name(self):
        return self.item_set.first().text
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

    @staticmethod
    def create_new(first_item_text, owner=None):
        list_ = List.objects.create(owner=owner)
        Item.objects.create(text=first_item_text, list=list_)
        return list_


class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)
    def __str__(self):
        return self.text
    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    

lists/forms.py
from django import forms
from lists.models import Item, List
from django.core.exceptions import ValidationError


EMPTY_ITEM_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):
    class Meta:
        model = Item
        fields = ('text', )
        widgets = {'text': forms.fields.TextInput(attrs={
        'placeholder': 'Enter a to-do item', 'class': 'form-control input-lg',
        }), }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
            }
   

class NewListForm(ItemForm):
    def save(self, owner):
        if owner.is_authenticated():
            return List.create_new(first_item_text=self.cleaned_data['text'], owner=owner)
        else:
            return List.create_new(first_item_text=self.cleaned_data['text'])

class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse

def persona_login(request):
    user = authenticate(assertion=request.POST['assertion'])
    if user:
        login(request, user)
        return HttpResponse('OK')
    return HttpResponse()

lists/views.py
from django.shortcuts import redirect, render
from lists.forms import ItemForm, ExistingListItemForm, NewListForm
from lists.models import Item, List
from django.contrib.auth import get_user_model

User = get_user_model()

def home_page(request):
    return render(request, 'home.html', {'form':ItemForm()})


def new_list(request):
    form = NewListForm(data=request.POST)
    
    if form.is_valid():
        list_ = form.save(owner=request.user)
        return redirect(list_)
    return render(request, 'home.html', {'form':form})

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, 'list.html', {'list': list_, "form": form})

def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, 'my_lists.html', {'owner':owner})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

<body>
<div class="container">

    <nav class="navbar navbar-default" role="navigation">
	    <a class="navbar-brand" href="/">Superlists</a>
		{% if user.email %}
		    <ul class="nav navbar-nav">
			    <li><a href="{% url 'my_lists' user.email %}">My lists</a></li>
			</ul>
		    <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">Log out</a>
			<span class="navbar-text navbar-right">Logged in as {{user.email}} </span>
		{% else %}
		    <a class="btn navbar-btn navbar-right" id="id_login" href="#">Sign in</a>
		{% endif %}
	</nav>

    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">
                <h1>{% block header_text %}{% endblock %}</h1>
				{% block list_form %}
                <form method="POST" action="{% block form_action %}{% endblock %}">
                    {{ form.text }}
                    {% csrf_token %}
					{% if form.errors %}
					    <div class="form-group has-error">
						    <div class="help-block">{{ form.text.errors }}</div>
						</div>
					{% endif %}
                </form>
				{% endblock %}
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}
        </div>
    </div>
	
	<div class="row">
	    <div class="col-md-6 col-md-offset-3">
		    {% block extra_content %}
			{% endblock %}
		</div>
	</div>

</div>
<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://login.persona.org/include.js"></script>
<script src="/static/list.js"></script>
<script src="/static/accounts.js"></script>

<script>
/*global $, Superlists, navigator */
    $(document).ready(function(){
	var user = "{{user.email}}"||null;
	var token = "{{csrf_token}}";
	var urls = { login: "{% url 'persona_login' %}", logout: "TODO",};
	Superlists.Accounts.initialize(navigator, user, token, urls);
	});
</script>
</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
            <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My lists{% endblock %}

{% block list_form %}{% endblock %}
{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
	<ul>
	    {% for list in owner.list_set.all %}
		    <li><a href="{{ list.get_absolute_url }}">{{list.name}}</a></li>
		{% endfor %}
	</ul>
{% endblock %}